`timescale 1ns / 1ps
//////////////////////////////////////////////////////////////////////////////////
// AY1718 Sem 1 EE2020 Project
// Project Name: Audio Effects
// Module Name: AUDIO_FX_TOP
// Team No.: 
// Student Names: 
// Matric No.:
// Description: 
// 
// Work Distribution:
//////////////////////////////////////////////////////////////////////////////////

module AUDIO_FX_TOP(
    input CLK,            // 100MHz FPGA clock
    
//    input lab1switch,
//    input lab2switch,
//    input lab3switch,
    input [15:0] sw,
    
    input [4:0] btn,
    
    input  J_MIC3_Pin3,   // PmodMIC3 audio input data (serial)
    output J_MIC3_Pin1,   // PmodMIC3 chip select, 20kHz sampling clock
    output J_MIC3_Pin4,   // PmodMIC3 serial clock (generated by module SPI.v)
     
    output J_DA2_Pin1,    // PmodDA2 sampling clock (generated by module DA2RefComp.vhd)
    output J_DA2_Pin2,    // PmodDA2 Data_A, 12-bit speaker output (generated by module DA2RefComp.vhd)
    output J_DA2_Pin3,    // PmodDA2 Data_B, not used (generated by module DA2RefComp.vhd)
    output J_DA2_Pin4,    // PmodDA2 serial clock, 50MHz clock
    
    output [7:0]row,      // Output to JXADC ports
    output [3:0]col,      // Output to JC ports

    
    output [15:0]led,
    output [3:0]an,
    output [6:0]seg,
    output dp
    );

    //////////////////////////////////////////////////////////////////////////////////
    // Clock Divider Module: Generate necessary clocks from 100MHz FPGA CLK
    // Please create the clock divider module and instantiate it here.

      wire clk_20k;
      wire clk_50M;
    
      FlexiClock cc20k(20000,CLK,clk_20k);
      FlexiClock cc2(50000000,CLK,clk_50M);
  
     //////////////////////////////////////////////////////////////////////////////////
     //SPI Module: Converting serial data into a 12-bit parallel register
     //Do not change the codes in this area
       wire [11:0]MIC_in;
       SPI u1 (CLK, clk_20k, J_MIC3_Pin3, J_MIC3_Pin1, J_MIC3_Pin4, MIC_in);
       
    /////////////////////////////////////////////////////////////////////////////////////
    // Real-time Audio Effect Features
    // Please create modules to implement different features and instantiate them here   
            
      wire [11:0]speaker_out;
      task_selector ts(CLK, MIC_in, sw, btn, led, an, seg, dp, speaker_out);
      
      
      // The following is demo-usage of the OutputRowCol module, similar to sseg module
      wire slow_clock;
      FlexiClock fc0(5, CLK, slow_clock);
      reg [4:0] count1 = 0;
      reg [4:0] count2 = 1;
      reg [4:0] count3 = 2;
      reg [4:0] count4 = 3;
      always @(posedge slow_clock) begin
        count1 <= (count1 == 7) ? 0 : count1 + 1; 
        count2 <= (count2 == 7) ? 0 : count2 + 1; 
        count3 <= (count3 == 7) ? 0 : count3 + 1; 
        count4 <= (count4 == 7) ? 0 : count4 + 1; 
      end
      
      OutputRowCol(CLK, 0, count1, count2, count3, count4, row, col);
      
    /////////////////////////////////////////////////////////////////////////////////////
    //DAC Module: Digital-to-Analog Conversion
    //Do not change the codes in this area        
      DA2RefComp u2(clk_50M, clk_20k, speaker_out, ,1'b0, J_DA2_Pin2, J_DA2_Pin3, J_DA2_Pin4, J_DA2_Pin1,);
        
    //////////////////////////////////////////////////////////////////////////////////
  
endmodule
