# 
# Synthesis run script generated by Vivado
# 

namespace eval rt {
    variable rc
}
set rt::rc [catch {
  uplevel #0 {
    set ::env(BUILTIN_SYNTH) true
    source $::env(HRT_TCL_PATH)/rtSynthPrep.tcl
    rt::HARTNDb_startJobStats
    set rt::cmdEcho 0
    rt::set_parameter writeXmsg true
    rt::set_parameter enableParallelHelperSpawn true
    set ::env(RT_TMP) "C:/Users/Francis/Desktop/EE2020_FINAL/EE2020_Design_Project/audio_effects.runs/synth_1/.Xil/Vivado-87676-Lee/realtime/tmp"
    if { [ info exists ::env(RT_TMP) ] } {
      file mkdir $::env(RT_TMP)
    }

    rt::delete_design

    set rt::partid xc7a35tcpg236-1

    set rt::multiChipSynthesisFlow false
    source $::env(SYNTH_COMMON)/common_vhdl.tcl
    set rt::defaultWorkLibName xil_defaultlib

    # Skipping read_* RTL commands because this is post-elab optimize flow
    set rt::useElabCache true
    if {$rt::useElabCache == false} {
      rt::read_verilog -include c:/Users/Francis/Desktop/EE2020_FINAL/EE2020_Design_Project/audio_effects.srcs/sources_1/ip/dist_mem_gen_0 {
      C:/Users/Francis/Desktop/EE2020_FINAL/EE2020_Design_Project/audio_effects.runs/synth_1/.Xil/Vivado-87676-Lee/realtime/dist_mem_gen_0_stub.v
      C:/Users/Francis/Desktop/EE2020_FINAL/EE2020_Design_Project/audio_effects.srcs/sources_1/imports/new/FlexiClock.v
      C:/Users/Francis/Desktop/EE2020_FINAL/EE2020_Design_Project/audio_effects.srcs/sources_1/new/SPI.v
      C:/Users/Francis/Desktop/EE2020_FINAL/EE2020_Design_Project/audio_effects.srcs/sources_1/new/averageavg2b.v
      C:/Users/Francis/Desktop/EE2020_FINAL/EE2020_Design_Project/audio_effects.srcs/sources_1/new/averagehigh2b.v
      C:/Users/Francis/Desktop/EE2020_FINAL/EE2020_Design_Project/audio_effects.srcs/sources_1/new/averageoff2b.v
      C:/Users/Francis/Desktop/EE2020_FINAL/EE2020_Design_Project/audio_effects.srcs/sources_1/imports/new/clockToSine8.v
      C:/Users/Francis/Desktop/EE2020_FINAL/EE2020_Design_Project/audio_effects.srcs/sources_1/imports/new/deciToDigits.v
      C:/Users/Francis/Desktop/EE2020_FINAL/EE2020_Design_Project/audio_effects.srcs/sources_1/imports/new/frequency_to_m.v
      C:/Users/Francis/Desktop/EE2020_FINAL/EE2020_Design_Project/audio_effects.srcs/sources_1/imports/new/generateSine.v
      C:/Users/Francis/Desktop/EE2020_FINAL/EE2020_Design_Project/audio_effects.srcs/sources_1/imports/new/m_to_clock.v
      C:/Users/Francis/Desktop/EE2020_FINAL/EE2020_Design_Project/audio_effects.srcs/sources_1/new/project_1.v
      C:/Users/Francis/Desktop/EE2020_FINAL/EE2020_Design_Project/audio_effects.srcs/sources_1/new/project_2b.v
      C:/Users/Francis/Desktop/EE2020_FINAL/EE2020_Design_Project/audio_effects.srcs/sources_1/new/project_3b.v
      C:/Users/Francis/Desktop/EE2020_FINAL/EE2020_Design_Project/audio_effects.srcs/sources_1/imports/new/sevenseg.v
      C:/Users/Francis/Desktop/EE2020_FINAL/EE2020_Design_Project/audio_effects.srcs/sources_1/imports/new/sineLUT.v
      C:/Users/Francis/Desktop/EE2020_FINAL/EE2020_Design_Project/audio_effects.srcs/sources_1/new/task2a.v
      C:/Users/Francis/Desktop/EE2020_FINAL/EE2020_Design_Project/audio_effects.srcs/sources_1/new/task3a.v
      C:/Users/Francis/Desktop/EE2020_FINAL/EE2020_Design_Project/audio_effects.srcs/sources_1/new/task_selector.v
      C:/Users/Francis/Desktop/EE2020_FINAL/EE2020_Design_Project/audio_effects.srcs/sources_1/new/AUDIO_FX_TOP.v
    }
      rt::read_vhdl -lib xil_defaultlib C:/Users/Francis/Desktop/EE2020_FINAL/EE2020_Design_Project/audio_effects.srcs/sources_1/imports/audio_effects.srcs/DA2CompRef.vhd
      rt::filesetChecksum
    }
    rt::set_parameter usePostFindUniquification true
    set rt::SDCFileList C:/Users/Francis/Desktop/EE2020_FINAL/EE2020_Design_Project/audio_effects.runs/synth_1/.Xil/Vivado-87676-Lee/realtime/AUDIO_FX_TOP_synth.xdc
    rt::sdcChecksum
    set rt::top AUDIO_FX_TOP
    set rt::reportTiming false
    rt::set_parameter elaborateOnly false
    rt::set_parameter elaborateRtl false
    rt::set_parameter eliminateRedundantBitOperator true
    rt::set_parameter writeBlackboxInterface true
    rt::set_parameter ramStyle auto
    rt::set_parameter merge_flipflops true
# MODE: 
    rt::set_parameter webTalkPath {C:/Users/Francis/Desktop/EE2020_FINAL/EE2020_Design_Project/audio_effects.cache/wt}
    rt::set_parameter enableSplitFlowPath "C:/Users/Francis/Desktop/EE2020_FINAL/EE2020_Design_Project/audio_effects.runs/synth_1/.Xil/Vivado-87676-Lee/"
    set ok_to_delete_rt_tmp true 
    if { [rt::get_parameter parallelDebug] } { 
       set ok_to_delete_rt_tmp false 
    } 
    if {$rt::useElabCache == false} {
        set oldMIITMVal [rt::get_parameter maxInputIncreaseToMerge]; rt::set_parameter maxInputIncreaseToMerge 1000
        set oldCDPCRL [rt::get_parameter createDfgPartConstrRecurLimit]; rt::set_parameter createDfgPartConstrRecurLimit 1
      rt::run_synthesis -module $rt::top
        rt::set_parameter maxInputIncreaseToMerge $oldMIITMVal
        rt::set_parameter createDfgPartConstrRecurLimit $oldCDPCRL
    }

    set rt::flowresult [ source $::env(SYNTH_COMMON)/flow.tcl ]
    rt::HARTNDb_stopJobStats
    rt::HARTNDb_reportJobStats "Synthesis Optimization Runtime"
    rt::HARTNDb_stopSystemStats
    if { $rt::flowresult == 1 } { return -code error }


  set hsKey [rt::get_parameter helper_shm_key] 
  if { $hsKey != "" && [info exists ::env(BUILTIN_SYNTH)] && [rt::get_parameter enableParallelHelperSpawn] && [info exists rt::doParallel] && $rt::doParallel} { 
     $rt::db killSynthHelper $hsKey
  } 
  rt::set_parameter helper_shm_key "" 
    if { [ info exists ::env(RT_TMP) ] } {
      if { [info exists ok_to_delete_rt_tmp] && $ok_to_delete_rt_tmp } { 
        file delete -force $::env(RT_TMP)
      }
    }

    source $::env(HRT_TCL_PATH)/rtSynthCleanup.tcl
  } ; #end uplevel
} rt::result]

if { $rt::rc } {
  $rt::db resetHdlParse
  set hsKey [rt::get_parameter helper_shm_key] 
  if { $hsKey != "" && [info exists ::env(BUILTIN_SYNTH)] && [rt::get_parameter enableParallelHelperSpawn] && [info exists rt::doParallel] && $rt::doParallel} { 
     $rt::db killSynthHelper $hsKey
  } 
  source $::env(HRT_TCL_PATH)/rtSynthCleanup.tcl
  return -code "error" $rt::result
}
